pretrained_model_name_or_path = "/home/darksidewalker/GitHub/DaSiWa-TrainFlow/internal/trainer"
qwen3 = "/home/darksidewalker/GitHub/DaSiWa-TrainFlow/internal/trainer"
vae = "/home/darksidewalker/GitHub/DaSiWa-TrainFlow/internal/trainer"
network_module = "networks.lora_anima"
network_dim = 48
network_alpha = 32
network_train_unet_only = false
gradient_checkpointing = true
max_grad_norm = 1.0
learning_rate = 1e-4
optimizer_type = ""
optimizer_args = ["weight_decay=0.01"]
lr_scheduler = "cosine"
max_train_steps = 1000
train_batch_size = 0
gradient_accumulation_steps = 0
mixed_precision = "bf16"
output_dir = "/tmp/test"
output_name = "test"
save_every_n_steps = 100
sample_every_n_steps = 100
sample_prompts = "/home/darksidewalker/GitHub/DaSiWa-TrainFlow/internal/trainer"
save_state = true
save_last_n_steps_state = 1
save_last_n_epochs_state = 1
sample_sampler = "euler"
timestep_sampling = "sigmoid"
discrete_flow_shift = 1.0
sigmoid_scale = 1.3
weighting_scheme = "logit_normal"
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
attn_mode = "torch"
save_model_as = "safetensors"
save_precision = "bf16"
max_data_loader_n_workers = 4
vae_chunk_size = 32
vae_disable_cache = true
seed = 0
